[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm ci --cache .npm --prefer-offline',
  'cd backend && npm ci --cache .npm --prefer-offline',
  'cd frontend && npm ci --cache .npm --prefer-offline'
]

[phases.build]
cmds = [
  'cd frontend && npm run build',
  'cd backend && npm run init-db'
]

[start]
cmd = 'cd backend && npm start'